class Solution(object):
    def findTheDifference(self, s, t):
        """
        PROBLEM STATEMENT:
        Given two strings s and t which consist of only lowercase letters.
        String t is generated by random shuffling string s and 
        then add one more letter at a random position.
        Find the letter that was added in t.
        :type s: str
        :type t: str
        :rtype: str
        """
        from collections import defaultdict
        
        dic = defaultdict(int)
        
        for char in t:
            dic[char] += 1
        
        for char in s:
            dic[char] -= 1
        
        for char,count in dic.items():
            if count == 1:
                return char
        return ""    
        
# ALTERNATE SOLUTION 

class Solution(object):
    def findTheDifference(self, s, t):
        """
        PROBLEM STATEMENT:
        Given two strings s and t which consist of only lowercase letters.
        String t is generated by random shuffling string s and 
        then add one more letter at a random position.
        Find the letter that was added in t.
        :type s: str
        :type t: str
        :rtype: str
        """
        import collections
        
        return (collections.Counter(t) - collections.Counter(s)).keys()[0]
        
# ANOTHER SOLUTION

class Solution(object):
    def findTheDifference(self, s, t):
        """
        PROBLEM STATEMENT:
        Given two strings s and t which consist of only lowercase letters.
        String t is generated by random shuffling string s and 
        then add one more letter at a random position.
        Find the letter that was added in t.
        :type s: str
        :type t: str
        :rtype: str
        """
        temp = 0
        for i in s:
            temp ^= ord(i)
        for j in t:
            temp ^= ord(j)
        return chr(temp)
        
